### ISSUE TITLE
singularity issue when run adap

### ISSUE THREAD

**Issue by ammorse** [zamboni-lab/SLAW#11]
Running the container with singularity on the test data after modifying the parameter.txt file for ADAP results in errors on both a linux workstation and a computing cluster - see attached adap.log file.  The only modifications done to the parameter file were 1) change line 143 from "false" to "true" and 2) change line 178 from "openMS" to "ADAP".  

The test data runs fine without modification to the parameter.txt file on the linux workstation and the cluster.   

Any suggestions would be appreciated!

Alison

[adap.log](https://github.com/zamboni-lab/SLAW/files/7841596/adap.log)

**Comment by adelabriere** [comment]
Hi @ammorse thanks for reporting your problem

There is a problem with the number of cores detected by SLAW here:

`2022-01-10|14:49:01|INFO: Total memory available: 374760 and 72 cores. The workflow will use 5278 Mb by core on 1 cores.`

SLAW use N-1 cores for optimization, in this case as there is 1 it is 0. I'll add an error message for that.

I am not sure exactly why but you can pass the number of cores that you use like this by passing the NCORES environment variables ie:

SINGULARITYENV_NCORES=10

It should solve the problem. If it does not or you find an exaplanation at why SLAW detect only 1 core please let me known.

**Comment by ammorse** [comment]
Thanks for the quick response!

I increased the cores to 12 but get the same error:

2022-01-10|15:34:49|INFO: Total memory available: 374100 and 72 cores. The workflow will use 5269 Mb by core on 12 cores.
2022-01-10|15:34:49|INFO: Guessing polarity from file:DDA1.mzML
2022-01-10|15:34:49|DEBUG: Rscript /pylcmsprocessing/Rscript/get_polarity.R "/input/DDA1.mzML" "/output/polarity"
2022-01-10|15:34:51|INFO: Polarity detected: positive
2022-01-10|15:34:51|DEBUG: Rscript /pylcmsprocessing/Rscript/createSQLiteexperiment.R -d '/input' -b '/output/temp_processing_db.sqlite'
2022-01-10|15:34:51|DEBUG: Rscript /pylcmsprocessing/Rscript/createSQLiteexperiment.R -d '/input' -b '/output/temp_processing_db.sqlite'
2022-01-10|15:34:52|INFO: STEP: initialisation TOTAL_TIME:2.61s LAST_STEP:2.61s
2022-01-10|15:34:52|DEBUG: Rscript /pylcmsprocessing/Rscript/createSQLiteexperiment.R -d '/input' -b '/output/temp_processing_db.sqlite'
2022-01-10|15:34:52|DEBUG: Rscript /pylcmsprocessing/Rscript/createSQLiteexperiment.R -d '/input' -b '/output/temp_processing_db.sqlite'
2022-01-10|15:34:53|INFO: Building input
2022-01-10|15:34:53|INFO: Computing MZmine parameters
2022-01-10|15:34:54|INFO: 4 existing peak picking 0 added.
2022-01-10|15:34:54|INFO: Building softwares
2022-01-10|15:34:54|INFO: Building peakpicking
2022-01-10|15:34:54|DEBUG: /MZmine-2.52-Linux/startMZmine-Linux "/output/ADAP/xml/xml_1_8724ba244b72587de8964b2845313a95.xml"
2022-01-10|15:34:54|DEBUG: /MZmine-2.52-Linux/startMZmine-Linux "/output/ADAP/xml/xml_2_ab56e050d8986b8f2c15ddd9de546b0a.xml"
2022-01-10|15:34:54|DEBUG: /MZmine-2.52-Linux/startMZmine-Linux "/output/ADAP/xml/xml_3_c9437a898051dd8ae8d7c7e3028deecd.xml"
2022-01-10|15:34:54|DEBUG: /MZmine-2.52-Linux/startMZmine-Linux "/output/ADAP/xml/xml_4_c5cfe1da97cf769434a67fb9d32a0002.xml"
2022-01-10|15:34:54|DEBUG: stderr:/bin/sh: 1: /MZmine-2.52-Linux/startMZmine-Linux: Permission denied


---

Alison Morse, PhD
2033 Mowry Rd, Room 120A
Molecular Genetics and Microbiology
University of Florida 32611
Gainesville, FL 32611
352-273-8123


________________________________

**Comment by adelabriere** [comment]
Sorry I looked at your issue fast and only focused on the last error.

I just retested the `adelabriere/slaw:latest` with ADAP optimization with singularity on my laptop and on our cluster and both worked as intended. ADAP may be the trickiest to run as MZmine is writing some temporary files internally. Here the command that I used to run the container:

`SINGULARITYENV_LOGGING=DEBUG SINGULARITYENV_MEMORY=XXXX SINGULARITYENV_NCORES=X singularity run -C -W work_dir -B your_input:/input  -B your_output:/output docker://adelabriere/slaw:latest`

-W work_dir needs to be a writable folder. I think that may be the cause of your problem.
-C is also required on our cluster.

The version of singularity that I used is singularity 3.6.1

Maybe adding these options will solve you problem ?

**Comment by ammorse** [comment]
Hi Alexis,

I'm still having issues running slaw with adap on your test data.  Getting the same error on my linux workstation and on a mac - see below.
Any suggestions?

Thanks!
Alison

INFO:    Using cached SIF image
2022-01-13|09:21:56|INFO: Total memory available: 379454 and 72 cores. The workflow will use 5269 Mb by core on 12 cores.
2022-01-13|09:21:56|INFO: Guessing polarity from file:DDA1.mzML
2022-01-13|09:21:56|DEBUG: Rscript /pylcmsprocessing/Rscript/get_polarity.R "/input/DDA1.mzML" "/output/polarity"
2022-01-13|09:22:02|INFO: Polarity detected: positive
2022-01-13|09:22:02|DEBUG: Rscript /pylcmsprocessing/Rscript/createSQLiteexperiment.R -d '/input' -b '/output/temp_processing_db.sqlite'
2022-01-13|09:22:02|DEBUG: Rscript /pylcmsprocessing/Rscript/createSQLiteexperiment.R -d '/input' -b '/output/temp_processing_db.sqlite'
2022-01-13|09:22:04|INFO: STEP: initialisation TOTAL_TIME:8.22s LAST_STEP:8.22s
2022-01-13|09:22:05|DEBUG: Rscript /pylcmsprocessing/Rscript/createSQLiteexperiment.R -d '/input' -b '/output/temp_processing_db.sqlite'
2022-01-13|09:22:05|DEBUG: Rscript /pylcmsprocessing/Rscript/createSQLiteexperiment.R -d '/input' -b '/output/temp_processing_db.sqlite'
2022-01-13|09:22:05|INFO: Building input
2022-01-13|09:22:05|INFO: Computing MZmine parameters
2022-01-13|09:22:07|INFO: 4 existing peak picking 0 added.
2022-01-13|09:22:07|INFO: Building softwares
2022-01-13|09:22:07|INFO: Building peakpicking
2022-01-13|09:22:07|INFO: Peak picking finished 0 files not processed on a total of 0
2022-01-13|09:22:07|INFO: No corrections to do
2022-01-13|09:22:07|DEBUG: Rscript /pylcmsprocessing/Rscript/extractingMGFfromMZML.R "/output/temp_processing_db.sqlite" "/output/ADAP/msms" 0.0 71 True
2022-01-13|09:22:07|DEBUG: stdout:Extracting all MS-MS spectra.
2022-01-13|09:22:07|DEBUG: stderr:Linking to: OpenSSL 1.1.1f  31 Mar 2020
MS-MS spectra extraction finished
2022-01-13|09:22:07|INFO: MS2 extraction finished
2022-01-13|09:22:07|INFO: Starting peaktable filtration
Traceback (most recent call last):
  File "/wrapper_docker.py", line 223, in <module>
    exp.filter_peaktables(filtering_string)
  File "/pylcmsprocessing/model/experiment.py", line 673, in filter_peaktables
    with multiprocessing.Pool(min(num_workers, len(all_peaktables))) as executor:
  File "/usr/lib/python3.8/multiprocessing/context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 205, in __init__
    raise ValueError("Number of processes must be at least 1")
ValueError: Number of processes must be at least 1

---

Alison Morse, PhD
2033 Mowry Rd, Room 120A
Molecular Genetics and Microbiology
University of Florida 32611
Gainesville, FL 32611
352-273-8123


________________________________

**Comment by adelabriere** [comment]
Hi, sorry to hear that. Thanks to you I just fixed this bug in e01577b48bdb8692df6a81a2462e619609c5300d. To finish the processing:

1. Remove the ADAP folder and restart.
2. Wait 10 minutes and use adelabriere/slaw:dev, I am running some test but I should integrate the change to adelabriere/slaw:latest this evening. So normally you could also just use adelabriere/slaw:latest tomorrow.

**Comment by ammorse** [comment]
Thanks Alexis!

Will try in a bit 🙂

Alison


---

Alison Morse, PhD
2033 Mowry Rd, Room 120A
Molecular Genetics and Microbiology
University of Florida 32611
Gainesville, FL 32611
352-273-8123


________________________________

**Comment by ammorse** [comment]
Hi Alexis,

running with docker://adelabriere/slaw:dev I get the following error

INFO:    Using cached SIF image
Traceback (most recent call last):
  File "/wrapper_docker.py", line 13, in <module>
    from pylcmsprocessing.model.helper.UI import UI
  File "/pylcmsprocessing/__init__.py", line 2, in <module>
    import model.experiment
  File "/pylcmsprocessing/model/experiment.py", line 674
    if min_process>0:
                    ^
SyntaxError: invalid syntax



---

Alison Morse, PhD
2033 Mowry Rd, Room 120A
Molecular Genetics and Microbiology
University of Florida 32611
Gainesville, FL 32611
352-273-8123


________________________________

**Comment by ammorse** [comment]
Hi Alexis,

Thanks for the help!  I pulled and reran your test data (docker://adelabriere/slaw:latest) using adap and height.  I think all is good but I am seeing some stderr/Error - see attached file (testData_adap.log).

Alison

---

Alison Morse, PhD
2033 Mowry Rd, Room 120A
Molecular Genetics and Microbiology
University of Florida 32611
Gainesville, FL 32611
352-273-8123


________________________________

**Comment by adelabriere** [comment]
Hi Alison, I don t see the attached file ? I can confirm however that there is an ADAP issue which was not there before, and I have a clear idea of its origin. I ll tag you here when everything is fixed and both singularity and docker run fine. Sorry for the lost time.

**Comment by adelabriere** [comment]
@ammorse The permission problem is fixed for both latest and dev and I was able to fully process the ADAP examples with both singularity and docker. I tried to setup some automated building but it was messing up the permission of MZmine. I hope it solves your last issue.

**Comment by ammorse** [comment]
Thanks Alexis!

I'll pull and give it a go.

Alison


---

Alison Morse, PhD
2033 Mowry Rd, Room 120A
Molecular Genetics and Microbiology
University of Florida 32611
Gainesville, FL 32611
352-273-8123


________________________________

**Comment by ammorse** [comment]
Ran with adap on your testdata after pulling and got the following error:

INFO:    Using cached SIF image
2022-01-14|10:08:58|INFO: Total memory available: 376777 and 72 cores. The workflow will use 5269 Mb by core on 12 cores.
2022-01-14|10:08:58|INFO: Guessing polarity from file:DDA1.mzML
2022-01-14|10:08:58|DEBUG: Rscript /pylcmsprocessing/Rscript/get_polarity.R "/input/DDA1.mzML" "/output/polarity"
2022-01-14|10:09:00|INFO: Polarity detected: positive
2022-01-14|10:09:00|DEBUG: Rscript /pylcmsprocessing/Rscript/createSQLiteexperiment.R -d '/input' -b '/output/temp_processing_db.sqlite'
2022-01-14|10:09:00|DEBUG: Rscript /pylcmsprocessing/Rscript/createSQLiteexperiment.R -d '/input' -b '/output/temp_processing_db.sqlite'
2022-01-14|10:09:00|INFO: STEP: initialisation TOTAL_TIME:1.98s LAST_STEP:1.98s
2022-01-14|10:09:01|DEBUG: Rscript /pylcmsprocessing/Rscript/createSQLiteexperiment.R -d '/input' -b '/output/temp_processing_db.sqlite'
2022-01-14|10:09:01|DEBUG: Rscript /pylcmsprocessing/Rscript/createSQLiteexperiment.R -d '/input' -b '/output/temp_processing_db.sqlite'
2022-01-14|10:09:01|INFO: Building input
2022-01-14|10:09:01|INFO: Computing MZmine parameters
2022-01-14|10:09:02|INFO: 4 existing peak picking 0 added.
2022-01-14|10:09:02|INFO: Building softwares
2022-01-14|10:09:02|INFO: Building peakpicking
2022-01-14|10:09:02|INFO: Peak picking finished 0 files not processed on a total of 0
2022-01-14|10:09:02|INFO: No corrections to do
2022-01-14|10:09:02|DEBUG: Rscript /pylcmsprocessing/Rscript/extractingMGFfromMZML.R "/output/temp_processing_db.sqlite" "/output/ADAP/msms" 0.0 12 True
2022-01-14|10:09:06|DEBUG: stdout:Extracting all MS-MS spectra.
2022-01-14|10:09:06|DEBUG: stderr:Linking to: OpenSSL 1.1.1f  31 Mar 2020
MS-MS spectra extraction finished
2022-01-14|10:09:06|INFO: MS2 extraction finished
2022-01-14|10:09:06|INFO: Starting peaktable filtration
2022-01-14|10:09:06|INFO: Done peaktables filtration
2022-01-14|10:09:06|INFO: STEP: peakpicking TOTAL_TIME:7.87s LAST_STEP:5.90s
2022-01-14|10:09:06|INFO: Alignment finished
2022-01-14|10:09:06|INFO: STEP: alignment TOTAL_TIME:7.88s LAST_STEP:0.00s
2022-01-14|10:09:06|DEBUG: Rscript /pylcmsprocessing/Rscript/gap_filling_refactored.R "/output/temp_processing_db.sqlite" "/output/datamatrices/datamatrix_50660bda0ce5a823e93a7cc9474963f6.csv" >
2022-01-14|10:09:17|DEBUG: stdout:<simpleError in mapply(FUN = FUN, ..., MoreArgs = MoreArgs, SIMPLIFY = SIMPLIFY): zero-length inputs cannot be mixed with those of non-zero length>
NULL
2022-01-14|10:09:17|DEBUG: stderr:Create profile matrix with method 'bin' and step 1 ... OK
Error in h5read(hdf5_file, path_infer) :
  Object 'FEATURES/MFEAT1_1' does not exist in this HDF5 file.
Calls: extractMissingInformationsAllBatches ... eval -> eval -> eval -> mapply -> <Anonymous> -> h5read
Execution halted
2022-01-14|10:09:17|INFO: Gap filling and isotopic pattern extraction finished.
2022-01-14|10:09:17|INFO: STEP: gap-filling TOTAL_TIME:18.81s LAST_STEP:10.94s
2022-01-14|10:09:17|INFO: Annotation finished
2022-01-14|10:09:17|INFO: STEP: annotation TOTAL_TIME:18.82s LAST_STEP:0.00s
2022-01-14|10:09:17|INFO: Processing finished.


---

Alison Morse, PhD
2033 Mowry Rd, Room 120A
Molecular Genetics and Microbiology
University of Florida 32611
Gainesville, FL 32611
352-273-8123


________________________________

**Comment by adelabriere** [comment]
Could you clean the output folder and retry just letting the parameters.txt file, it seems like you have artifact from an old processing. I think it should solve this.

**Comment by ammorse** [comment]
my bad! cleaned output dir and reran with test data and adap - got output!
going to try with a subset of our data next


---

Alison Morse, PhD
2033 Mowry Rd, Room 120A
Molecular Genetics and Microbiology
University of Florida 32611
Gainesville, FL 32611
352-273-8123


________________________________

**Comment by ammorse** [comment]
with my data I'm getting a Java error:

INFO:    Using cached SIF image
2022-01-14|10:59:53|INFO: Total memory available: 376406 and 72 cores. The workflow will use 4 Mb by core on 12 cores.
2022-01-14|10:59:53|INFO: Guessing polarity from file:b1_aos_129.mzML
2022-01-14|10:59:53|DEBUG: Rscript /pylcmsprocessing/Rscript/get_polarity.R "/input/b1_aos_129.mzML" "/output/polarity"
2022-01-14|10:59:55|INFO: Polarity detected: positive
2022-01-14|10:59:55|DEBUG: Rscript /pylcmsprocessing/Rscript/createSQLiteexperiment.R -d '/input' -b '/output/temp_processing_db.sqlite'
2022-01-14|10:59:55|DEBUG: Rscript /pylcmsprocessing/Rscript/createSQLiteexperiment.R -d '/input' -b '/output/temp_processing_db.sqlite'
2022-01-14|10:59:56|INFO: STEP: initialisation TOTAL_TIME:2.48s LAST_STEP:2.48s
2022-01-14|10:59:56|INFO: An ADAP batch file has been generated in the /output directory, you ca use it to refine peakpicking parameters using MZmine.
2022-01-14|10:59:56|DEBUG: Rscript /pylcmsprocessing/Rscript/createSQLiteexperiment.R -d '/input' -b '/output/temp_processing_db.sqlite'
2022-01-14|10:59:56|DEBUG: Rscript /pylcmsprocessing/Rscript/createSQLiteexperiment.R -d '/input' -b '/output/temp_processing_db.sqlite'
2022-01-14|10:59:57|INFO: Building input
2022-01-14|10:59:57|INFO: Computing MZmine parameters
2022-01-14|10:59:58|INFO: 0 existing peak picking 11 added.
2022-01-14|10:59:58|INFO: Building softwares
2022-01-14|10:59:58|INFO: Building peakpicking
2022-01-14|10:59:58|DEBUG: /MZmine-2.52-Linux/startMZmine-Linux "/output/ADAP/xml/xml_1_e7ce7e8c6b7cb3d7d48fec2c7d71ebec.xml"
2022-01-14|10:59:58|DEBUG: /MZmine-2.52-Linux/startMZmine-Linux "/output/ADAP/xml/xml_2_970dc76067207d1b924d080e643d84aa.xml"
2022-01-14|10:59:58|DEBUG: /MZmine-2.52-Linux/startMZmine-Linux "/output/ADAP/xml/xml_3_4a617aa20e4f048f0cdc85d5559d7783.xml"
2022-01-14|10:59:58|DEBUG: /MZmine-2.52-Linux/startMZmine-Linux "/output/ADAP/xml/xml_4_c96b35725531166fbfd80129e0080993.xml"
2022-01-14|10:59:58|DEBUG: /MZmine-2.52-Linux/startMZmine-Linux "/output/ADAP/xml/xml_5_2eb6635caec00b3cd7344bc8f5cdac4f.xml"
2022-01-14|10:59:58|DEBUG: /MZmine-2.52-Linux/startMZmine-Linux "/output/ADAP/xml/xml_6_d8eaa1acf475e1ceaa29dce505a2e374.xml"
2022-01-14|10:59:58|DEBUG: /MZmine-2.52-Linux/startMZmine-Linux "/output/ADAP/xml/xml_7_08577539ac4063c4667e9f24375d02df.xml"
2022-01-14|10:59:58|DEBUG: /MZmine-2.52-Linux/startMZmine-Linux "/output/ADAP/xml/xml_8_95f4493cd78798cb00428dd4c0301f9c.xml"
2022-01-14|10:59:58|DEBUG: /MZmine-2.52-Linux/startMZmine-Linux "/output/ADAP/xml/xml_9_92d8c6e96856e8b1044ded7b67752030.xml"
2022-01-14|10:59:58|DEBUG: /MZmine-2.52-Linux/startMZmine-Linux "/output/ADAP/xml/xml_10_2cb78523b3e947fcd9ae0c93e8bd7979.xml"
2022-01-14|10:59:58|DEBUG: /MZmine-2.52-Linux/startMZmine-Linux "/output/ADAP/xml/xml_11_91ad051e8c2a9f4eb5fd74602a4b485c.xml"
2022-01-14|10:59:58|DEBUG: stderr:Invalid maximum heap size: -Xmx-196m
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.




---

Alison Morse, PhD
2033 Mowry Rd, Room 120A
Molecular Genetics and Microbiology
University of Florida 32611
Gainesville, FL 32611
352-273-8123


________________________________

**Comment by ammorse** [comment]
should the java parameter not have a hyphen?  -Xmx196m instead of -Xmx-196m?

---

Alison Morse, PhD
2033 Mowry Rd, Room 120A
Molecular Genetics and Microbiology
University of Florida 32611
Gainesville, FL 32611
352-273-8123


________________________________

**Comment by adelabriere** [comment]
You are right on the hyphen. You seem to have passed too little memory ` The workflow will use 4 Mb by core` on 12 cores, did you use the -e MEMORY=XXX ? If so increase it.

**Comment by ammorse** [comment]
Ah, I see.  I increased the memory and it now starts java but there are still some java errors .  Runs for a minute or so then fails - see attached log file.

A


---

Alison Morse, PhD
2033 Mowry Rd, Room 120A
Molecular Genetics and Microbiology
University of Florida 32611
Gainesville, FL 32611
352-273-8123


________________________________

**Comment by adelabriere** [comment]
Thanks for the test @ammorse , I still don t see the attached log. I don t see anything attached.

**Comment by adelabriere** [comment]
Thanks I see it now ! I never have never experienced this issue, it seems to be related to a specific permission problem on your machine similar to this one:
**https://stackoverflow.com/questions/67732682/how-to-change-dconf-directory**
So maybe adding `-B /run/user/your_username` will help.
 Is there anything specific in your machine singularity setup ?

**Comment by ammorse** [comment]
I tried your suggestion - see attached updated log file.  It's odd the test data runs on my machine but not a set of my data.  I'm using singularity 3.8.3.  
[testBrieData_adap.log](https://github.com/zamboni-lab/SLAW/files/7872185/testBrieData_adap.log)

**Comment by adelabriere** [comment]
HI @ammorse  thanks we are getting there, the mzmine error just indicates that there is no peak detected at all, all the problematic errors are gone. It is an mzmine thing not a SLAW thing. This just means that the default parameters for ADAP are not adapted for you, I will add a message for this, I admit that ADAP is the one I use the least so it is clearly less polished. SLAW should be able to find better parameters if you just set `need_optimization` to `true`.

I guess that the previous problem could be related to the location form which you launch singularity.

**Comment by ammorse** [comment]
Thanks Alexis! Will try with optimization

**Comment by ammorse** [comment]
Got it to run successfully with a subset of our data!!!  Thanks Alexis!
Alison
